"""relationship between users and pins

Revision ID: 2b88a3c959f5
Revises: 856288275035
Create Date: 2023-02-10 18:53:53.358676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b88a3c959f5"
down_revision = "856288275035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pins", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "pins", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pins", type_="foreignkey")
    op.drop_column("pins", "user_id")
    # ### end Alembic commands ###
