"""added user table

Revision ID: 48dedb088a2c
Revises: 
Create Date: 2023-02-06 09:32:47.754617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48dedb088a2c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
