"""added file_key

Revision ID: 5488b90e539b
Revises: 73aa3647cea0
Create Date: 2023-07-23 21:23:53.936407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488b90e539b'
down_revision = '73aa3647cea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_samples', sa.Column('file_key', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_samples', 'file_key')
    # ### end Alembic commands ###
