"""Adding audio_clips table

Revision ID: 73aa3647cea0
Revises: 834d9828f5c3
Create Date: 2023-07-22 16:14:09.872012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73aa3647cea0'
down_revision = '834d9828f5c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_samples',
    sa.Column('s3_url', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_samples')
    # ### end Alembic commands ###
