"""added created_at and updated_at

Revision ID: 834d9828f5c3
Revises: c42f9ebd93f4
Create Date: 2023-07-18 21:51:23.380784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834d9828f5c3'
down_revision = 'c42f9ebd93f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pins', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('pins', 'updated_at')
    op.drop_column('pins', 'created_at')
    # ### end Alembic commands ###
