"""added pin table and updated schemas

Revision ID: 856288275035
Revises: 48dedb088a2c
Create Date: 2023-02-06 16:26:16.525853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856288275035'
down_revision = '48dedb088a2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('longitude', sa.DECIMAL(precision=8, scale=5), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=8, scale=5), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins')
    # ### end Alembic commands ###
